name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/cocoapods@master
      - name: Run Snyk to check for vulnerabilities
        run: synk test --all-projects --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
